VALID_OBJECT_TYPES = {
    'MESH', 'CURVE', 'SURFACE', 'META', 'FONT', 'CURVES', 'POINTCLOUD'
}

AUTO_CAMERA_COLLECTION_NAME = "__VIEWTEXFORGE_CAMERAS__"
AUTO_LIGHT_COLLECTION_NAME = "__VIEWTEXFORGE_LIGHTS__"
TEMP_VIEWPORT_CAMERA_NAME = "__ViewTexForge_ViewportCam__"
MATCAP_NAME = None
CLAY_VIEWPORT_COLOR = (0.8, 0.8, 0.8)
CAPTURE_MARGIN = 1.05
